version: '3.8'

services:
  web01:
    build:
      context: ./web01
    container_name: web01
    networks:
      private_network:
        ipv4_address: 192.168.1.110
    ports:
      - "8080:80"
      - "2222:22" # SSH port mapping
    dns:
      - 8.8.8.8  # Example DNS server

  app01:
    build:
      context: ./app01
    container_name: app01
    networks:
      private_network:
        ipv4_address: 192.168.1.111
    mem_limit: 1024m
    ports:
      - "8081:8080"
      - "2223:22" # SSH port mapping
    dns:
      - 8.8.8.8  # Example DNS server

  rmq01:
    build:
      context: ./rmq01
    container_name: rmq01
    networks:
      private_network:
        ipv4_address: 192.168.1.112
    ports:
      - "8082:5672"
      - "2224:22" # SSH port mapping
    dns:
      - 8.8.8.8  # Example DNS server

  mc01:
    build:
      context: ./mc01
    container_name: mc01
    networks:
      private_network:
        ipv4_address: 192.168.1.113
    ports:
      - "8083:11211"
      - "2225:22" # SSH port mapping
    dns:
      - 8.8.8.8  # Example DNS server

  db01:
    build:
      context: ./db01
    container_name: db01
    networks:
      private_network:
        ipv4_address: 192.168.1.114
    ports:
      - "8084:3306"
      - "2226:22" # SSH port mapping
    dns:
      - 8.8.8.8  # Example DNS server

networks:
  private_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.1.0/24
      
  public:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.1.0/24
